### ISSUE TITLE
Add contributors to readme

### ISSUE THREAD

**Issue by yochannah** [learnopenscience/TOPS-OC1-ethos#2]
Paging the SMEs and others who have worked on content - add your github username here and we'll add you to the contributors list.

**Comment by marimeireles** [comment]
Ping =)

**Comment by Ismael-KG** [comment]
Ping ping ping!

**Comment by aosman12** [comment]
Hey !!

**Comment by msundukova** [comment]
Hello!

**Comment by TomoCoral** [comment]
Hi :)

**Comment by rmcgranaghan** [comment]
Hi! I have not yet contributed much, but am planning to join the group to help however possible. Been away for awhile in July for various other work commitments, but am more available in the coming weeks/months
