### ISSUE TITLE
Lesson 3 : Suggestion to Add Another Case Scenario

### ISSUE THREAD

**Issue by acolum** [learnopenscience/TOPS-OC1-ethos#5]
## General Instructions
- [x] I've read the [Code of Conduct](https://www.agu.org/Plan-for-a-Meeting/AGUMeetings/Meetings-Resources/Meetings-code-of-conduct) and agree to follow it 
- [x] The issue is specific and provides clear suggestions on how to resolve it
- [x] File name and line number(s) are included 

## Type of Issue
Check only one:  
- [x] Something is missing
- [] Something is incorrect
- [] Reference(s) need fixing
** Note: Please do not submit spelling and grammar issues ** (copyediting will follow)

## Get Credit
In order to get credit for your issue(s), register at [https://forms.gle/UAedD4J6raxbfvnH8](https://forms.gle/UAedD4J6raxbfvnH8).

My suggestion is to include a fourth case scenario under the "How diverse stakeholders are included in open science" heading (lines 25-33 of lesson3.md) that describes the process of organizing an inclusive hybrid (i.e., both physical and virtual) event. Hybrid events are often organized differently than solely physical or virtual events and have unique challenges that must be kept in mind. I've included a few helpful resources below that may help in the writing of this case scenario. I also think that having four case scenarios under the "How diverse stakeholders are included in open science" heading would nicely mirror the four case scenarios under the "How each group contributes to Open Science" heading above it.

- [Emerging Standards and the Hybrid Model for Organizing Scientific Events During and After the COVID-19 Pandemic](https://www.cambridge.org/core/journals/disaster-medicine-and-public-health-preparedness/article/emerging-standards-and-the-hybrid-model-for-organizing-scientific-events-during-and-after-the-covid19-pandemic/6B8DDCE7D11CC68304F1E61FBA3B9FA5)
- [The Right Mix: Making a Hybrid Conference Work for All](https://www.nature.com/articles/d41586-022-01797-7)

If you have any questions about this issue, please let me know. Thank you for all of your time and effort in putting this module together.

**Comment by yochannah** [comment]
Thanks @acolum, this is a great suggestion! I also like both of the links you have there, which talk about things realistically and note that you need to put extra safety for physical events and extra organisation for hybrid/online components.

**Comment by yochannah** [comment]
Also - @acolum - thinking ahead. Possibly next week (module leads have a big get-together next week) or the week after, we might want to write this case scenario. Would you be interested in being looped in to help co-author or suggest content?

**Comment by acolum** [comment]
Thanks so much, @yochannah. I'd be delighted to help co-author or suggest content.
